package ch.supsi.connectfour.frontend.model;

import ch.supsi.connectfour.backend.application.connectfour.ConnectFourBackendController;
import ch.supsi.connectfour.backend.application.connectfour.ConnectFourBusinessInterface;
import ch.supsi.connectfour.backend.application.event.GameEvent;
import ch.supsi.connectfour.backend.business.player.ConnectFourPlayerInterface;
import org.jetbrains.annotations.Nullable;

import java.io.File;

public class ConnectFourModel {

    /* self reference */
    private static ConnectFourModel instance;

    /* backend controller */
    private final ConnectFourBackendController backendController;

    private ConnectFourModel() {
        this.backendController = ConnectFourBackendController.getInstance();
    }

    /**
     *
     * @return an instance of this class
     */
    public static ConnectFourModel getInstance() {
        if (instance == null) {
            instance = new ConnectFourModel();
        }
        return instance;
    }

    /**
     * delegate move request to the backend controller
     * @param column Column in which the insertion is desired
     * @return The event generated by the move
     */
    public GameEvent playerMove(int column) {
        return this.backendController.playerMove(column);
    }

    /**
     *
     * @return true if the match is null, false otherwise
     */
    public boolean isCurrentMatchNull() {
        return this.backendController.getCurrentMatch() == null;
    }

    /**
     * delegate 'create new game' request to the backend controller
     */
    public void createNewGame() {
        this.backendController.createNewGame();
    }

    /**
     * delegate 'persist' request to the backend controller
     */
    public boolean persist() {
        return this.backendController.persist();
    }

    //ALEX
    public boolean persist(File directory, String filename) {
        return this.backendController.persist(directory, filename);
    }

    /**
     *
     * @return the saving name associated with the current match
     */
    public String getSaveName() {
        return this.backendController.getSaveName();
    }

    /**
     * tries to load a match from a file
     * @param file File from which the game is intended to be loaded
     * @return The loaded game, null if it could not be loaded
     */
    public @Nullable ConnectFourBusinessInterface tryLoadingSave(File file) {
        return this.backendController.tryLoadingSave(file);
    }

    /**
     * Returns the player who is not currently playing
     * @param player current player
     * @return other player
     */
    public ConnectFourPlayerInterface getOtherPlayer(ConnectFourPlayerInterface player) {
        return this.backendController.getOtherPlayer(player);
    }
}
